### ISSUE TITLE
Playground txrefs missing colon `:`

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-did-tools-js#2]
For transaction `2f1838f481be7b4f4d37542a751aa3a27be7114f798feb24ff0fc764730973d0`

the playground is displaying `did:btcrxz35-jzv2-qqs2-9wjt` but it should be `did:btcr:xz35-jzv2-qqs2-9wjt` — it is missing a colon. This is also true for the generated DID Document examples.

**Comment by kimdhamilton** [comment]
Fixed with 7257ccc
